JovemProgramadorMVC10/Models/Aluno.cs
namespace JovemProgramadorMVC10.Models
{
    public class Aluno
    {
        public int Id { get; set; }
        public string Matricula { get; set; }
        public string Nome { get; set; }
        public string Cpf { get; set; }
    }
}

JovemProgramadorMVC10/Models/ErrorViewModel.cs
namespace JovemProgramadorMVC10.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JovemProgramadorMVC10/Models/Professor.cs
namespace JovemProgramadorMVC10.Models
{
    public class Professor
    {
        public int Id { get; set; }
        public string Disciplina { get; set; }
        public string Nome { get; set; }
        public string Cpf { get; set; }
    }
}

JovemProgramadorMVC10/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;

namespace JovemProgramadorMVC10.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        public string Senha { get; set; }
        public string Email { get; set; }
    }
}

JovemProgramadorMVC10/Controllers/AlunoController.cs
using JovemProgramadorMVC10.Data.Repositorio.Interfaces;
using JovemProgramadorMVC10.Models;
using Microsoft.AspNetCore.Mvc;

namespace JovemProgramadorMVC10.Controllers
{
    public class AlunoController : Controller
    {
        private readonly IAlunoRepositorio _alunoRepositorio;
        public AlunoController(IAlunoRepositorio alunoRepositorio)
        {
            _alunoRepositorio = alunoRepositorio;
        }
        public IActionResult Index()
        {
            var aluno = _alunoRepositorio.BuscarAlunos();
            return View(aluno);
        }
        public IActionResult AdicionarAluno()
        {
            return View();
        }
        public IActionResult InserirAluno(Aluno aluno) 
        {
            try
            {
                _alunoRepositorio.InserirAluno(aluno);
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("Index");   
        }
        public IActionResult Editar(int id)
        {
            var aluno = _alunoRepositorio.BuscarId(id);
            return View(aluno);

        }
        public IActionResult EditarAluno(Aluno aluno)
        {
            _alunoRepositorio.EditarAluno(aluno);
            return RedirectToAction("Index");
        }
        public IActionResult Excluir(int id)
        {
            var aluno = _alunoRepositorio.BuscarId(id);
            return View(aluno);
        }
        public IActionResult ExcluirAluno(Aluno aluno)
        {
            _alunoRepositorio.ExcluirAluno(aluno);
            return RedirectToAction("Index"); 
        }
    }
}

JovemProgramadorMVC10/Controllers/HomeController.cs
using JovemProgramadorMVC10.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace JovemProgramadorMVC10.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JovemProgramadorMVC10/Controllers/LoginController.cs
using JovemProgramadorMVC10.Data.Repositorio.Interfaces;
using JovemProgramadorMVC10.Models;
using Microsoft.AspNetCore.Mvc;

namespace JovemProgramadorMVC10.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        public LoginController(IUsuarioRepositorio usuarioRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ValidarLogin(string email, string senha)
        {
            if(ModelState.IsValid) 
            {
                var usuarioValidado = _usuarioRepositorio.ValidarUsuario(email, senha);
                if (usuarioValidado != null)
                {
                    // Login bem-sucedido, redirecionar para a página principal
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    // Falha na validação do usuário
                    ModelState.AddModelError("", "Nome de usuário ou senha inválidos");
                    
                }
            }
            return View("Index");
        }
    }
}

JovemProgramadorMVC10/Controllers/ProfessorController.cs
using JovemProgramadorMVC10.Data.Repositorio.Interfaces;
using JovemProgramadorMVC10.Models;
using Microsoft.AspNetCore.Mvc;

namespace JovemProgramadorMVC10.Controllers
{
    public class ProfessorController : Controller
    {
        private readonly IProfessorRepositorio _professorRepositorio;
        public ProfessorController(IProfessorRepositorio professorRepositorio)
        {
            _professorRepositorio = professorRepositorio;
        }
        public IActionResult Index()
        {
            var professor = _professorRepositorio.BuscarProfessores();
            return View(professor);
        }
        public IActionResult AdicionarProfessor()
        {
            return View();
        }
        public IActionResult InserirProfessor(Professor professor)
        {
            try
            {
                _professorRepositorio.InserirProfessor(professor);
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("Index");
        }
        public IActionResult Editar(int id)
        {
            var professor = _professorRepositorio.BuscarId(id);
            return View(professor);

        }
        public IActionResult EditarProfessor(Professor professor)
        {
            _professorRepositorio.EditarProfessor(professor);
            return RedirectToAction("Index");
        }
        public IActionResult Excluir(int id)
        {
            var professor = _professorRepositorio.BuscarId(id);
            return View(professor);
        }
        public IActionResult ExcluirProfessor(Professor professor)
        {
            _professorRepositorio.ExcluirProfessor(professor);
            return RedirectToAction("Index");
        }
    }
}

JovemProgramadorMVC10/Views/Aluno/AdicionarAluno.cshtml
@model Aluno

@{
    ViewData["Title"] = "Cadastrar aluno";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de alunos</h1>
    </div>

    <form asp-controller="Aluno" asp-action="InserirAluno" method="post">

        <div class="mb-3">
            <label class="form-label">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Insira o nome do aluno">
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>

        <div class="mb-3">
            <label class="form-label">Matricula</label>
            <input type="text" asp-for="Matricula" class="form-control" placeholder="Insira a matricula do aluno">
         </div>

        <div class="mb-3">
            <label class="form-label">Cpf</label>
            <input type="text" asp-for="Cpf" class="form-control" placeholder="Insira o CPF do aluno">
            <span class="text-danger" asp-validation-for="Cpf"></span>
        </div>


        <div class="d-flex gap-5 mt-5">
            @*Botão Cadastrar*@
			<button type="submit" class="btn btn-primary w-50">Cadastrar</button>
			@*Botão Voltar*@
			<a class="btn btn-primary w-50" asp-controller="Aluno" asp-action="Index">Voltar</a>
        </div>

    </form>

</div>

JovemProgramadorMVC10/Views/Aluno/Editar.cshtml
@model Aluno

@{
    ViewData["Title"] = "Editar aluno";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Edição de alunos</h1>
    </div>

    <form asp-controller="Aluno" asp-action="EditarAluno" method="post">

        <input type="hidden" asp-for="Id" />

        <div class="mb-3">
            <label for="Nome" class="form-label text-light">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Nome do aluno">
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>

        <div class="mb-3">
            <label for="Matricula" class="form-label text-light">Matricula</label>
            <input type="text" asp-for="Matricula" class="form-control" placeholder="Matricula do aluno">
        </div>

        <div class="mb-3">
            <label for="Cpf" class="form-label text-light">Cpf</label>
            <input type="text" asp-for="Cpf" class="form-control" placeholder="CPF do aluno">
            <span class="text-danger" asp-validation-for="Cpf"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            @*Botão Editar*@
            <button type="submit" class="btn btn-primary w-50">Editar</button>
            @*Botão Voltar*@
            <a class="btn btn-primary w-50" asp-controller="Aluno" asp-action="Index">Voltar</a>
        </div>

    </form>

</div>

JovemProgramadorMVC10/Views/Aluno/ExcluirAluno.cshtml
@model Aluno

@{
    ViewData["Title"] = "Excluir aluno";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Excluir aluno</h1>
    </div>

    <form asp-controller="Aluno" asp-action="ExcluirAluno" method="post">

        <input type="hidden" asp-for="Id" />

        <h2 class="text-warning">Tem certeza que deseja excluir o registro?</h2>

        <div class="mb-3">
            <label class="form-label text-light">Nome</label>
            <input type="text" asp-for="Nome" class="form-control">
        </div>

        <div class="mb-3">
            <label class="form-label text-light">Matricula</label>
            <input type="text" asp-for="Matricula" class="form-control ">
        </div>

        <div class="mb-3">
            <label class="form-label text-light">Cpf</label>
            <input type="text" asp-for="Cpf" class="form-control ">
        </div>

        <div class="text-center d-flex gap-5 mt-5">
            @*Botão Excluir*@
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            @*Botão Voltar*@
            <a class="btn btn-primary w-50" asp-controller="Aluno" asp-action="Index">Voltar</a>
        </div>
    </form>

</div>

JovemProgramadorMVC10/Views/Aluno/Index.cshtml
@model List<Aluno>

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Alunos</h1>
        <a class="btn btn-primary mx-2" type="button" asp-controller="Aluno" asp-action="AdicionarAluno">Cadastrar novo aluno</a>
    </div>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Matricula</th>
                <th scope="col">Nome</th>
                <th scope="col">Cpf</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (Aluno aluno in Model)
                {
                    <tr>
                        <td>@aluno.Matricula </td>
                        <td>@aluno.Nome </td>
                        <td>@aluno.Cpf </td>
                        <td>
                            <a type="submit" class="btn btn-warning mx-2" role="button" asp-controller="Aluno" asp-action="Editar" asp-route-id="@aluno.Id"><i class="bi bi-pen mx-2"></i>Editar</a>
                            <a type="submit" class="btn btn-danger mx-2" role="button" asp-controller="Aluno" asp-action="ExcluirAluno" asp-route-id="@aluno.Id"><i class="bi bi-trash3 mx-2"></i>Excluir</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

JovemProgramadorMVC10/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

JovemProgramadorMVC10/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="d-flex justify-content-center align-items-center min-vh-100">
        <div class="login-box bg-light p-5 rounded">
            <h1 class="text-center mb-4">Login</h1>
            <form class="login" method="post" asp-controller="Login" asp-action="ValidarLogin">
                <div class="mb-3">
                    <label for="inputEmail4" class="form-label">Email</label>
                    <input type="email" class="form-control" id="inputEmail4" name="email" required>
                </div>
                <div class="mb-3">
                    <label for="inputPassword4" class="form-label">Senha</label>
                    <input type="password" class="form-control" id="inputPassword4" name="senha" required>
                </div>
                <div class="d-grid gap-2">
                    <button class="btn btn-primary" type="submit">Entrar</button>
                    <button class="btn btn-cadastro" type="button">Cadastre-se</button>
                </div>
                @* Mensagem de erro *@
                @if (!ViewData.ModelState.IsValid)
                {
                    <div style="color: red;">
                        @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                        {
                            <p>@error.ErrorMessage</p>
                        }
                    </div>
                }
            </form>
        </div>
    </div>
</div>

JovemProgramadorMVC10/Views/Professor/AdicionarProfessor.cshtml
@model Professor

@{
    ViewData["Title"] = "Cadastrar professor";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de professores</h1>
    </div>

    <form asp-controller="Professor" asp-action="InserirProfessor" method="post">

        <div class="mb-3">
            <label class="form-label">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Insira o nome do professor">
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>

        <div class="mb-3">
            <label class="form-label">Disciplina</label>
            <input type="text" asp-for="Disciplina" class="form-control" placeholder="Insira a disciplina do professor">
            <span class="text-danger" asp-validation-for="Disciplina"></span>
        </div>

        <div class="mb-3">
            <label class="form-label">Cpf</label>
            <input type="text" asp-for="Cpf" class="form-control" placeholder="Insira o CPF do professor">
            <span class="text-danger" asp-validation-for="Cpf"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            @*Botão Cadastrar*@
            <button type="submit" class="btn btn-primary w-50">Cadastrar</button>
            @*Botão Voltar*@
            <a class="btn btn-primary w-50" asp-controller="Professor" asp-action="Index">Voltar</a>
        </div>

    </form>

</div>

JovemProgramadorMVC10/Views/Professor/Editar.cshtml
@model Professor

@{
    ViewData["Title"] = "Editar professor";
}


<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Edição de professores</h1>
    </div>

    <form asp-controller="Professor" asp-action="EditarProfessor" method="post">

        <input type="hidden" asp-for="Id" />

        <div class="mb-3">
            <label for="Nome" class="form-label text-light">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Nome do professor">
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>

        <div class="mb-3">
            <label for="Disciplina" class="form-label text-light">Disciplina</label>
            <input type="text" asp-for="Disciplina" class="form-control" placeholder="Disciplina do professor">
        </div>

        <div class="mb-3">
            <label for="Cpf" class="form-label text-light">Cpf</label>
            <input type="text" asp-for="Cpf" class="form-control" placeholder="CPF do professor">
            <span class="text-danger" asp-validation-for="Cpf"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            @*Botão Editar*@
            <button type="submit" class="btn btn-primary w-50">Editar</button>
            @*Botão Voltar*@
            <a class="btn btn-primary w-50" asp-controller="Professor" asp-action="Index">Voltar</a>
        </div>

    </form>

</div>

JovemProgramadorMVC10/Views/Professor/ExcluirProfessor.cshtml
@model Professor

@{
    ViewData["Title"] = "Excluir professor";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Excluir aluno</h1>
    </div>

    <form asp-controller="Professor" asp-action="ExcluirProfessor" method="post">

        <input type="hidden" asp-for="Id" />

        <h2 class="text-warning">Tem certeza que deseja excluir o registro?</h2>

        <div class="mb-3">
            <label class="form-label text-light">Nome</label>
            <input type="text" asp-for="Nome" class="form-control">
        </div>

        <div class="mb-3">
            <label class="form-label text-light">Disciplina</label>
            <input type="text" asp-for="Disciplina" class="form-control ">
        </div>

        <div class="mb-3">
            <label class="form-label text-light">Cpf</label>
            <input type="text" asp-for="Cpf" class="form-control ">
        </div>

        <div class="text-center d-flex gap-5 mt-5">
            @*Botão Excluir*@
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            @*Botão Voltar*@
            <a class="btn btn-primary w-50" asp-controller="Professor" asp-action="Index">Voltar</a>
        </div>
    </form>

</div>

JovemProgramadorMVC10/Views/Professor/Index.cshtml
@model List<Professor>

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Professores</h1>
        <a class="btn btn-primary mx-2" type="button" asp-controller="Professor" asp-action="AdicionarProfessor">Cadastrar novo professor</a>
    </div>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Disciplina</th>
                <th scope="col">Nome</th>
                <th scope="col">Cpf</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (Professor professor in Model)
                {
                    <tr>
                        <td>@professor.Disciplina </td>
                        <td>@professor.Nome </td>
                        <td>@professor.Cpf </td>
                        <td>
                            <a type="submit" class="btn btn-warning mx-2" role="button" asp-controller="Professor" asp-action="Editar" asp-route-id="@professor.Id"><i class="bi bi-pen mx-2"></i>Editar</a>
                            <a type="submit" class="btn btn-danger mx-2" role="button" asp-controller="Professor" asp-action="ExcluirProfessor" asp-route-id="@professor.Id"><i class="bi bi-trash3 mx-2"></i>Excluir</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

JovemProgramadorMVC10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jovem Programador MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Ardosia.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JovemProgramadorMVC10.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-dark" asp-area="" asp-controller="Home" asp-action="Index">Jovem Programador</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!--ocutar botões na tela de login-->
                @if (ViewContext.RouteData.Values["controller"].ToString() != "Login" || ViewContext.RouteData.Values["action"].ToString() != "Index")
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Professor" asp-action="Index">Professores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Conhecimentos</a>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2024 - JovemProgramadorMVC10 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

JovemProgramadorMVC10/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JovemProgramadorMVC10</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JovemProgramadorMVC10.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
      
    </header>
    <div class="container">

        <div class="ImagemHome"</div>

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   @*  <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - JovemProgramadorMVC10 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

JovemProgramadorMVC10/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JovemProgramadorMVC10</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JovemProgramadorMVC10.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
       @*  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JovemProgramador</a>
                <button class="navbar-toggler" ,type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Professor" asp-action="Index">Professores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Conhecimentos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   @*  <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - JovemProgramadorMVC10 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>